name: nightly

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@5ade09c7bb116530f1b4d1cd06cfe20c8a3472b7 # tag=cargo-llvm-cov
