name: nightly

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@d8c10dae823f48238abff23fee4146b448aed2f1 # tag=cargo-llvm-cov
